site_name: ToolBox
copyright: Copyright &copy; 2024 RPLODEV
theme: 
  features:
    - navigation.footer
  name: material
  icon:
    logo: material/infinity
  font:
    #text: Merriweather Sans
    code: Red Hat Mono
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: green
      accent: deep purple
    
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: blue
      accent: deep orange
extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@james-willett
    - icon: simple/linkedin
      link: https://linkedin.com/in/willettjames

nav:
  - Home: index.md
  - Markdown:
    - 'Les titres': 'markdown/titres.md'
    - 'Les paragraphes': 'markdown/paragraphes.md'
    - 'La mise en forme': 'markdown/mise_en_forme_texte.md'
    - 'Les blocs de citation': 'markdown/citations.md'
    - 'Les lignes horizontales': 'markdown/lignes_horizontales.md'
    - 'Les liens hypertexte': 'markdown/liens_hypertexte.md'


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true