site_name: RPlodev TIPS
site_description: Mes divers Tips Network/DevOps/IT
copyright: Copyright &copy; 2024 RPLODEV

repo_url: https://github.com/rplodev/toolbox
repo_name: rplodev/toolbox

theme: 
  features:
    - navigation.footer
    - navigation.tracking
    - content.code.copy
  name: material
  palette:
    - scheme: slate
      primary: custom
      accent: custom

extra_css:
  - assets/stylesheets/custom.css

extra:
  social:
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/romuald-palomo/

nav:
  - Home: index.md
  - Docker:
    - "Sauvegarde d'images": 'docker/image_sauvegarde.md'
    - "Restauration d'images": 'docker/image_restauration.md'
  - Markdown:
    - 'Les titres': 'markdown/titres.md'
    - 'Les paragraphes': 'markdown/paragraphes.md'
    - 'La mise en forme': 'markdown/mise_en_forme_texte.md'
    - 'Les blocs de citation': 'markdown/citations.md'
    - 'Les lignes horizontales': 'markdown/lignes_horizontales.md'
    - 'Les liens hypertexte': 'markdown/liens_hypertexte.md'

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true